"""student academic fields

Revision ID: 0f2aa569be31
Revises: c96645284f7d
Create Date: 2026-02-17 10:14:05.108813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2aa569be31'
down_revision = 'c96645284f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('usn', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('section', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('section')
        batch_op.drop_column('usn')
        batch_op.drop_column('semester')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
