"""Add face fields properly

Revision ID: 4a16b3e42872
Revises: 90458341a78a
Create Date: 2026-02-14 21:42:41.976873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a16b3e42872'
down_revision = '90458341a78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_embedding', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('face_registered', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('embedding_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('embedding_updated_at')
        batch_op.drop_column('face_registered')
        batch_op.drop_column('face_embedding')

    # ### end Alembic commands ###
