"""security alert evidence fields

Revision ID: 4f6caa4e81a1
Revises: 8a9c8e0aec96
Create Date: 2026-02-17 12:51:27.906001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6caa4e81a1'
down_revision = '8a9c8e0aec96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similarity_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distance_meters', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resolved_by', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_alerts', schema=None) as batch_op:
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('distance_meters')
        batch_op.drop_column('similarity_score')

    # ### end Alembic commands ###
