"""add session feedback

Revision ID: adf7424e1094
Revises: 4f6caa4e81a1
Create Date: 2026-02-19 13:30:19.244589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf7424e1094'
down_revision = '4f6caa4e81a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_feedback_course_id'))
        batch_op.create_index(batch_op.f('ix_feedback_session_id'), ['session_id'], unique=False)
        batch_op.create_foreign_key('fk_feedback_session_id', 'attendance_sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_feedback_session_id'))
        batch_op.create_index(batch_op.f('ix_feedback_course_id'), ['course_id'], unique=False)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
