"""fix failed_attempts default

Revision ID: c96645284f7d
Revises: 584d18709bfd
Create Date: 2026-02-16 11:18:12.397091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96645284f7d'
down_revision = '584d18709bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('failed_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('failed_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
