"""Added intrusion protection

Revision ID: d10c5024e0b1
Revises: 4a16b3e42872
Create Date: 2026-02-15 14:38:29.506939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10c5024e0b1'
down_revision = '4a16b3e42872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_failed_attempt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('last_failed_attempt')
        batch_op.drop_column('failed_attempts')

    # ### end Alembic commands ###
